### PR TITLE
Pre-install minimum hardware requirements check on host system

### LINKED ISSUE #116: Add a check to ensure that the VM has enough memory, vcpus and disk size prior to install

### PR DESCRIPTION
**Pull request by agopala95**
Fixes #116 

Added a check to ensure minimum hardware specifications are met on host system that is used to install Nephio. The current requirements are as follows (taken from [nephio-ansible-install/README.md](https://github.com/nephio-project/one-summit-22-workshop/blob/main/nephio-ansible-install/README.md)):
- CPU RAM : 32 GB
- vCPUs: 8
- Disk space: 50 GB 

These values can be added by the user while creating the default inventory file _inventory/nephio.yaml_ and plugged in against the following variables:
- _host_min_vcpu_ : Minimum required number of vCPUs
- _host_min_cpu_ram_ : Minimum required CPU RAM value in GB
- _host_min_root_disk_space_ : Minimum required disk space (root disk partition for Linux distros) value in GB

The ansible play will now display warnings and pause for user prompts if any of the above requirements are not met (the current specification will also be displayed). Based on user prompts, the user can skip warnings and proceed with installation or abort the install entirely.

Key things to note:
1. This check would currently work only for systems that host Linux distros that belong to either the RedHat OS family or the Debian OS family as per Ansible.
2. The disk space requirement check is done only on the root disk partition.

List of files changed:
 - [nephio-ansible-install/playbooks/install-prereq.yaml](https://github.com/nephio-project/one-summit-22-workshop/blob/main/nephio-ansible-install/playbooks/install-prereq.yaml)
 - [nephio-ansible-install/README.md](https://github.com/nephio-project/one-summit-22-workshop/blob/main/nephio-ansible-install/README.md)
 - [nephio-ansible-install/nind/nephio.yaml](https://github.com/nephio-project/one-summit-22-workshop/blob/main/nephio-ansible-install/nind/nephio.yaml)

### CODE REVIEW

**Comment by vjayaramrh** [comment]
@henderiw @s3wong @aravind254 FYI

**Comment by henderiw** [comment]
I would prefer to specify this in the nephio.yaml file as input. Reason being if we change this going fwd it would not be hardcoded in the play task but rather be user defined. It also allows for people to use less if they want to e.g. use mgmt cluster only for testing purposes. etc.

**Comment by agopala95** [comment]
That's great input. I'm also wondering how to address default values for the above mentioned minimum requirements in case the user does not specify them, considering the nephio.yaml file is created by the user before installation. Introducing a default variable file and a readme file for it seem like a solution unless there's a better alternative.

**Comment by agopala95** [comment]
Thanks for the input. I've included the variables for the user to plug in within the _nephio.yaml_ file during its creation.

**Review by vjayaramrh — APPROVED** [review]

**Comment by vjayaramrh** [comment]
@henderiw @johnbelamaric FYI

**Pull request merged**
