### PR TITLE
Create post provision configuration script

### PR DESCRIPTION
**Pull request by electrocucaracha**
The `configure.sh` bash script pretends to automate some workshop instructions.

### CODE REVIEW

**Comment by joaofeteira** [comment]
maybe this has to be included in the ansible scripts right @sandeepAarna  ? to tackle the remaining points on @johnbelamaric  comment https://github.com/nephio-project/one-summit-22-workshop/issues/5#issuecomment-1309668554

**Comment by vjayaramrh** [comment]
> maybe this has to be included in the ansible scripts right @sandeepAarna ? to tackle the remaining points on @johnbelamaric comment [#5 (comment)](https://github.com/nephio-project/one-summit-22-workshop/issues/5#issuecomment-1309668554)

@electrocucaracha is this ready to be merged? if Yes @johnbelamaric I can include this in the ansible scripts

**Comment by electrocucaracha** [comment]
> @electrocucaracha is this ready to be merged? if Yes @johnbelamaric I can include this in the ansible scripts
No, it's not ready. Let me run a E2E test to include the latest changes.

**Comment by electrocucaracha** [comment]
@vjayaramrh @johnbelamaric This PR includes all the instructions until the installation of nephio system. Can you check the missing steps?

**Pull request merged**
