### PR TITLE
Add Diagram setup

### PR DESCRIPTION
**Pull request by debeaueric**
Add a diagram to illustrate the various elements deployed during the workshop

### CODE REVIEW

**Comment by johnbelamaric** [comment]
@vjayaramrh LGTY? This would be at least an initial part of #3 - we may want to add an MD file with the details and embedding this diagram.

**Comment by vjayaramrh** [comment]
> @vjayaramrh LGTY? This would be at least an initial part of #3 - we may want to add an MD file with the details and embedding this diagram.

Definitely this diagram is a great start and thanks to @debeaueric .
OS details of VM (including CPU, RAM, storage) , KIND version details and other details can be in the README.

@debeaueric , I believe if the diagram can be updated with below would add a lot of value (a picture is worth thousand words )
a)info indicating number of control-plane/worker nodes for each of the clusters 
b)CNI plugins installed on each of clusters
The above info will have to come from @sandeepAarna as he seems to have a deployment of free5gc working on KIND clusters.
What are your thoughts?

**Comment by johnbelamaric** [comment]
Maybe two diagrams, one that just shows the cluster without node details, then we can add a second diagram showing the internal of each cluster? I guess "internals" could mean nodes & networks and also could mean workloads. Those are probably separate diagrams too. The workloads maybe isn't needed, as it is shown on the first diagram. So, two diagrams, one high level and one showing a drill into a cluster.

**Comment by electrocucaracha** [comment]
According to this diagram, there is one KinD cluster (with Multus CNI) which is not part of the VM. Is that right?. In the other hand, Multus Networks will be one per edge cluster? I'm still trying to understand the use case for Multus here.

**Comment by johnbelamaric** [comment]
> According to this diagram, there is one KinD cluster (with Multus CNI) which is not part of the VM. Is that right?. In the other hand, Multus Networks will be one per edge cluster? I'm still trying to understand the use case for Multus here.

No, that's a "drill in" - we should put it in a different diagram, it came up on the call this morning as a bit confusing.

**Comment by debeaueric** [comment]
I agree, the kind details may be confusing. As discussed yesterday, we should have different diagrams:
- overview
- cluster details (nb of workers, CNI, any other useful info) with networking details between various workload clusters 
- networking details between 5GF component (eg display functional interfaces N3, N4, N6 and technical interfaces)  
Other description such as VM details (base image, tools installed with version) should be in a README

**Comment by johnbelamaric** [comment]
going to merge this for now but let's follow up with the multiple, updated diagrams

**Pull request merged**
